"""portfolio snaps model

Revision ID: 69981da75f0f
Revises: a8836ed7ddd4
Create Date: 2021-12-05 19:36:55.438901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69981da75f0f'
down_revision = 'a8836ed7ddd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_snaps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_snaps')
    # ### end Alembic commands ###
