"""empty message

Revision ID: a8836ed7ddd4
Revises: a644c8896fc6
Create Date: 2021-12-05 15:55:50.775975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8836ed7ddd4'
down_revision = 'a644c8896fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlists', sa.Column('stock_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'watchlists', 'stocks', ['stock_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watchlists', type_='foreignkey')
    op.drop_column('watchlists', 'stock_id')
    # ### end Alembic commands ###
