"""empty message

Revision ID: bbae34d990ec
Revises: 
Create Date: 2021-12-04 20:33:01.340968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbae34d990ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('ceo', sa.String(length=20), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('headquarters', sa.String(length=50), nullable=False),
    sa.Column('founded', sa.Integer(), nullable=False),
    sa.Column('market_cap', sa.String(), nullable=False),
    sa.Column('price_earnings_ratio', sa.Float(), nullable=False),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('average_volume', sa.String(), nullable=False),
    sa.Column('high_today', sa.Float(), nullable=False),
    sa.Column('low_today', sa.Float(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('volume', sa.String(), nullable=False),
    sa.Column('week52_high', sa.Float(), nullable=False),
    sa.Column('week52_low', sa.Float(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('market_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'news_id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('stocks')
    # ### end Alembic commands ###
